export const ActionTypes = {
  COINS: "COINS",
  TRENDING: "TRENDING",
  SINGLE_COIN: "SINGLE_COIN",
  SINGLE_COIN_CATEGORIES: "SINGLE_COIN_CATEGORIES",
  SINGLE_COIN_TICKERS: "SINGLE_COIN_TICKERS",
  CURRENCY: "CURRENCY",
  DAYS: "DAYS",
};